[package]
name = "p2sharer"
version = "1.0.0"
description = "P2Sharer - Serverless P2P Screen & Process Audio Sharing"
authors = ["P2Sharer Team"]
edition = "2021"

[lib]
name = "p2sharer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
cc = "1"

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
rfd = "0.15"
arboard = "3.6.1"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
reqwest = { version = "0.13", default-features = false, features = ["json", "native-tls"] }
tokio = { version = "1", features = ["full"] }
sysinfo = "0.32"
byteorder = "1.5"
base64 = "0.22"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
xcap = "0.9.8"
tokio-tungstenite = "0.24"
futures-util = "0.3"
getrandom = "0.2"
sha2 = "0.10"
webrtc = "=0.17.2"
bytes = "1"
dirs = "6"
rayon = "1.10"
jpeg-encoder = { version = "0.7.1", features = ["simd"] }
turbojpeg = { version = "1.5", default-features = false, features = ["cmake", "require-simd"] }
windows-capture = "2.0.1"
fast_image_resize = "5.1"
tauri-plugin-updater = "2.13.1"
tauri-plugin-process = "2.4.0"


[target.'cfg(windows)'.dependencies]
windows-capture-api = { package = "windows", version = "0.62.2", features = ["Win32_Graphics_Direct3D11", "Win32_Graphics_Direct3D_Fxc", "Win32_Graphics_Dxgi_Common"] }
webview2-com = "0.39.1"
windows = { version = "0.58", features = [
    "implement",
    "Win32_Foundation",
    "Win32_Media",
    "Win32_Media_Audio",
    "Win32_Media_Audio_Endpoints",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Variant",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dwm",
    "Win32_Security",
    "Win32_Security_Cryptography",
    "Win32_UI_Shell",
    "Win32_Storage_FileSystem",
    "Win32_System_JobObjects",
    "Win32_System_Diagnostics_ToolHelp"
] }
windows-core = "0.58"
